### PR TITLE
Prevent error if there is no stream in the episode.json

### LINKED ISSUE #34: missing video results in Error
In case a video cannot be found https://github.com/Opencast-Moodle/moodle-filter_opencast/blob/master/filter.php#L136 throws an error temporary fix for our instance was to include an `isset($data['streams']) &&` proposed by @justusdieckmann.

image
```
Fehler: count(): Argument #1 ($value) must be of type Countable|array, null given

[Weitere Informationen über diesen Fehler](http://docs.moodle.org/400/de/error/moodle/generalexceptionmessage)
Debug-Info: 
Error code: generalexceptionmessage
Stack trace: 

    line 131 of /filter/opencast/filter.php: TypeError thrown
    line 176 of /lib/filterlib.php: call to filter_opencast->filter()
    line 218 of /lib/filterlib.php: call to filter_manager->apply_filter_chain()
    line 372 of /lib/filterlib.php: call to filter_manager->filter_text()
    line 1303 of /lib/weblib.php: call to performance_measuring_filter_manager->filter_text()
    line 95 of /course/format/classes/output/local/content/section/summary.php: call to format_text()
    line 76 of /course/format/classes/output/local/content/section/summary.php: call to core_courseformat\output\local\content\section\summary->format_summary_text()
    line 145 of /course/format/classes/output/local/content/section.php: call to core_courseformat\output\local\content\section\summary->export_for_template()
    line 46 of /course/format/topics/classes/output/courseformat/content/section.php: call to core_courseformat\output\local\content\section->export_for_template()
    line 160 of /course/format/classes/output/local/content.php: call to format_topics\output\courseformat\content\section->export_for_template()
    line 86 of /course/format/classes/output/local/content.php: call to core_courseformat\output\local\content->export_sections()
    line 497 of /lib/outputrenderers.php: call to core_courseformat\output\local\content->export_for_template()
    line 108 of /course/format/classes/output/section_renderer.php: call to plugin_renderer_base->render()
    line 60 of /course/format/topics/format.php: call to core_courseformat\output\section_renderer->render()
    line 270 of /course/view.php: call to require()
 ```

### PR DESCRIPTION
**Pull request by justusdieckmann**

### CODE REVIEW

**Comment by justusdieckmann** [comment]
Fixes #34

**Comment by NinaHerrmann** [comment]
Hey @justusdieckmann,
as we introduced an error message in https://github.com/Opencast-Moodle/moodle-mod_opencast/pull/44/files we might as well do this here.  :thinking: 
I guess it is very unlikely, but also more consistent.

**Comment by justusdieckmann** [comment]
You're right, I've added that :)

**Comment by NinaHerrmann** [comment]
looks good to me @ferishili any thoughts on this? :)

**Comment by ferishili** [comment]
That looks good to me as well

**Comment by NinaHerrmann** [comment]
Thank you!

**Pull request merged**
